# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gum_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'gum_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gum_service.proto\x12\x0bgum_service\"h\n\x0bObservation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\robserver_name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\"H\n\x16\x41\x64\x64ObservationsRequest\x12.\n\x0cobservations\x18\x01 \x03(\x0b\x32\x18.gum_service.Observation\";\n\x17\x41\x64\x64ObservationsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2j\n\nGumService\x12\\\n\x0f\x41\x64\x64Observations\x12#.gum_service.AddObservationsRequest\x1a$.gum_service.AddObservationsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gum_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OBSERVATION']._serialized_start=34
  _globals['_OBSERVATION']._serialized_end=138
  _globals['_ADDOBSERVATIONSREQUEST']._serialized_start=140
  _globals['_ADDOBSERVATIONSREQUEST']._serialized_end=212
  _globals['_ADDOBSERVATIONSRESPONSE']._serialized_start=214
  _globals['_ADDOBSERVATIONSRESPONSE']._serialized_end=273
  _globals['_GUMSERVICE']._serialized_start=275
  _globals['_GUMSERVICE']._serialized_end=381
# @@protoc_insertion_point(module_scope)
