// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: gum_service/proto/gum_service.proto

package gumpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GumService_AddObservations_FullMethodName = "/gum_service.GumService/AddObservations"
)

// GumServiceClient is the client API for GumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GumServiceClient interface {
	AddObservations(ctx context.Context, in *AddObservationsRequest, opts ...grpc.CallOption) (*AddObservationsResponse, error)
}

type gumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGumServiceClient(cc grpc.ClientConnInterface) GumServiceClient {
	return &gumServiceClient{cc}
}

func (c *gumServiceClient) AddObservations(ctx context.Context, in *AddObservationsRequest, opts ...grpc.CallOption) (*AddObservationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddObservationsResponse)
	err := c.cc.Invoke(ctx, GumService_AddObservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GumServiceServer is the server API for GumService service.
// All implementations must embed UnimplementedGumServiceServer
// for forward compatibility.
type GumServiceServer interface {
	AddObservations(context.Context, *AddObservationsRequest) (*AddObservationsResponse, error)
	mustEmbedUnimplementedGumServiceServer()
}

// UnimplementedGumServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGumServiceServer struct{}

func (UnimplementedGumServiceServer) AddObservations(context.Context, *AddObservationsRequest) (*AddObservationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddObservations not implemented")
}
func (UnimplementedGumServiceServer) mustEmbedUnimplementedGumServiceServer() {}
func (UnimplementedGumServiceServer) testEmbeddedByValue()                    {}

// UnsafeGumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GumServiceServer will
// result in compilation errors.
type UnsafeGumServiceServer interface {
	mustEmbedUnimplementedGumServiceServer()
}

func RegisterGumServiceServer(s grpc.ServiceRegistrar, srv GumServiceServer) {
	// If the following call panics, it indicates UnimplementedGumServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GumService_ServiceDesc, srv)
}

func _GumService_AddObservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddObservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GumServiceServer).AddObservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GumService_AddObservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GumServiceServer).AddObservations(ctx, req.(*AddObservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GumService_ServiceDesc is the grpc.ServiceDesc for GumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gum_service.GumService",
	HandlerType: (*GumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddObservations",
			Handler:    _GumService_AddObservations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gum_service/proto/gum_service.proto",
}
