// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: gateway/proto/action_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        *ActionItem            `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateActionRequest) Reset() {
	*x = CreateActionRequest{}
	mi := &file_gateway_proto_action_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActionRequest) ProtoMessage() {}

func (x *CreateActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_action_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActionRequest.ProtoReflect.Descriptor instead.
func (*CreateActionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_action_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateActionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateActionRequest) GetAction() *ActionItem {
	if x != nil {
		return x.Action
	}
	return nil
}

type GetActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // e.g., "pending", "completed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionsRequest) Reset() {
	*x = GetActionsRequest{}
	mi := &file_gateway_proto_action_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsRequest) ProtoMessage() {}

func (x *GetActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_action_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionsRequest.ProtoReflect.Descriptor instead.
func (*GetActionsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_action_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetActionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetActionsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type UpdateActionStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionId      string                 `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	NewState      string                 `protobuf:"bytes,2,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActionStateRequest) Reset() {
	*x = UpdateActionStateRequest{}
	mi := &file_gateway_proto_action_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActionStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActionStateRequest) ProtoMessage() {}

func (x *UpdateActionStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_action_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActionStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateActionStateRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_action_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateActionStateRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *UpdateActionStateRequest) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

type ActionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // e.g., "reminder", "calendar_event"
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"` // e.g., "Calendar", "Notification"
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`   // JSON or structured data
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`       // "pending", "done", etc.
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionItem) Reset() {
	*x = ActionItem{}
	mi := &file_gateway_proto_action_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionItem) ProtoMessage() {}

func (x *ActionItem) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_action_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionItem.ProtoReflect.Descriptor instead.
func (*ActionItem) Descriptor() ([]byte, []int) {
	return file_gateway_proto_action_service_proto_rawDescGZIP(), []int{3}
}

func (x *ActionItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ActionItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ActionItem) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ActionItem) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ActionItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ActionItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *ActionItem            `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_gateway_proto_action_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_action_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_action_service_proto_rawDescGZIP(), []int{4}
}

func (x *ActionResponse) GetAction() *ActionItem {
	if x != nil {
		return x.Action
	}
	return nil
}

type GetActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*ActionItem          `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActionsResponse) Reset() {
	*x = GetActionsResponse{}
	mi := &file_gateway_proto_action_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActionsResponse) ProtoMessage() {}

func (x *GetActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_action_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActionsResponse.ProtoReflect.Descriptor instead.
func (*GetActionsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_action_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetActionsResponse) GetActions() []*ActionItem {
	if x != nil {
		return x.Actions
	}
	return nil
}

var File_gateway_proto_action_service_proto protoreflect.FileDescriptor

const file_gateway_proto_action_service_proto_rawDesc = "" +
	"\n" +
	"\"gateway/proto/action_service.proto\x12\aswagata\"[\n" +
	"\x13CreateActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x06action\x18\x02 \x01(\v2\x13.swagata.ActionItemR\x06action\"B\n" +
	"\x11GetActionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"T\n" +
	"\x18UpdateActionStateRequest\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x1b\n" +
	"\tnew_state\x18\x02 \x01(\tR\bnewState\"\xdc\x01\n" +
	"\n" +
	"ActionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"=\n" +
	"\x0eActionResponse\x12+\n" +
	"\x06action\x18\x01 \x01(\v2\x13.swagata.ActionItemR\x06action\"C\n" +
	"\x12GetActionsResponse\x12-\n" +
	"\aactions\x18\x01 \x03(\v2\x13.swagata.ActionItemR\aactions2\xee\x01\n" +
	"\rActionService\x12E\n" +
	"\fCreateAction\x12\x1c.swagata.CreateActionRequest\x1a\x17.swagata.ActionResponse\x12E\n" +
	"\n" +
	"GetActions\x12\x1a.swagata.GetActionsRequest\x1a\x1b.swagata.GetActionsResponse\x12O\n" +
	"\x11UpdateActionState\x12!.swagata.UpdateActionStateRequest\x1a\x17.swagata.ActionResponseB\x16Z\x14gateway/server/pb;pbb\x06proto3"

var (
	file_gateway_proto_action_service_proto_rawDescOnce sync.Once
	file_gateway_proto_action_service_proto_rawDescData []byte
)

func file_gateway_proto_action_service_proto_rawDescGZIP() []byte {
	file_gateway_proto_action_service_proto_rawDescOnce.Do(func() {
		file_gateway_proto_action_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_action_service_proto_rawDesc), len(file_gateway_proto_action_service_proto_rawDesc)))
	})
	return file_gateway_proto_action_service_proto_rawDescData
}

var file_gateway_proto_action_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gateway_proto_action_service_proto_goTypes = []any{
	(*CreateActionRequest)(nil),      // 0: swagata.CreateActionRequest
	(*GetActionsRequest)(nil),        // 1: swagata.GetActionsRequest
	(*UpdateActionStateRequest)(nil), // 2: swagata.UpdateActionStateRequest
	(*ActionItem)(nil),               // 3: swagata.ActionItem
	(*ActionResponse)(nil),           // 4: swagata.ActionResponse
	(*GetActionsResponse)(nil),       // 5: swagata.GetActionsResponse
}
var file_gateway_proto_action_service_proto_depIdxs = []int32{
	3, // 0: swagata.CreateActionRequest.action:type_name -> swagata.ActionItem
	3, // 1: swagata.ActionResponse.action:type_name -> swagata.ActionItem
	3, // 2: swagata.GetActionsResponse.actions:type_name -> swagata.ActionItem
	0, // 3: swagata.ActionService.CreateAction:input_type -> swagata.CreateActionRequest
	1, // 4: swagata.ActionService.GetActions:input_type -> swagata.GetActionsRequest
	2, // 5: swagata.ActionService.UpdateActionState:input_type -> swagata.UpdateActionStateRequest
	4, // 6: swagata.ActionService.CreateAction:output_type -> swagata.ActionResponse
	5, // 7: swagata.ActionService.GetActions:output_type -> swagata.GetActionsResponse
	4, // 8: swagata.ActionService.UpdateActionState:output_type -> swagata.ActionResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_proto_action_service_proto_init() }
func file_gateway_proto_action_service_proto_init() {
	if File_gateway_proto_action_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_action_service_proto_rawDesc), len(file_gateway_proto_action_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_action_service_proto_goTypes,
		DependencyIndexes: file_gateway_proto_action_service_proto_depIdxs,
		MessageInfos:      file_gateway_proto_action_service_proto_msgTypes,
	}.Build()
	File_gateway_proto_action_service_proto = out.File
	file_gateway_proto_action_service_proto_goTypes = nil
	file_gateway_proto_action_service_proto_depIdxs = nil
}
